
export default function RootLayout({
    children,
}) {
    return (
        <html lang="ar">
            <head>

                <title>Create Next App</title>
                <meta content='width=device-width, initial-scale=1' name='viewport' />
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />

            </head>
            <body>
                <main className="main">{children}</main>
            </body>
        </html>
    );
}